# -*- coding: utf-8 -*-
"""Classes e conversões.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18eLUjo0W40qUc-rUmaSGvIZdKfxpNkGs
"""

x = 10
type(x)
print('x', type(x))

nome ="Igor"
type(nome)
print("nome" , type(nome))

num = "100"
type(num)
print("num" , type(num))
num_convert = int(num)
print('num_convert', type(num_convert))

num_float = float(num)
print("num_float" , type(num_float))

nome = input("Digite seu nome ")
print(nome)

idade = input("Digite sua idade")
print("a idade entrou coomo uma variavel" , type(idade))
idade_int_convert = int(idade)
print("Dentro da Variavel 'Idade_Int_Convert' a Idade foi convertida para", type(idade_int_convert))

