# -*- coding: utf-8 -*-
"""Variações e Utilizações de for e while.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Qq54aw_cyq0uqn9ksOk_Ax2_QDH-Lhf
"""

contador = 1 , 2 , 3 , 4 , 5 , 6 , 7 , 8 , 9
print(contador)

# For Range
for contador in range(10):
  print(contador)

#For Range + Break
for contador in range(100):
    print(contador)
    if contador ==12:
      break

lista = ["Teste1", "Teste2"]
#For Simples
for val in lista:
  print(val)
#For Enumerate
for i, val in enumerate(lista):
  print(i,val)

lista2 = [2,3,4]
for val in lista2:
  val += 1
  print(val)
separação = ('_______')
print(separação)
for val in lista2:
  val *= 2
  print(val)

val = 1
while (val < 6):
  val *=2
  print(val)

# while com else
val = 1
while val < 6:
  val *= 2
else:
  print("valor de val é" , val)